name: git pages 部署

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Golang Init
      run: |
        go get github.com/yuin/goldmark
        go get github.com/yuin/goldmark-highlighting
    
    - name: Build
      run: go build -o cider *.go
    
    - name: Generate
      run: ./cider
